version: "3.9"
services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskflow_network

  backend:
    build: ./api-backend 
    container_name: api-backend
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: development
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    volumes:
      - ./api-backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - taskflow_network
    command: sh -c "npx sequelize-cli db:migrate && npm start"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${API_URL}
    container_name: react_frontend
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - API_URL=${API_URL}
      - REACT_APP_API_URL=${API_URL}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - taskflow_network


networks:
  taskflow_network:
    driver: bridge

volumes:
  postgres_data:
